/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as UnassistedIndexRouteImport } from './routes/unassisted/index'
import { Route as UnassistedAudioRouteImport } from './routes/unassisted/audio'
import { Route as UnassistedBeamerRouteImport } from './routes/unassisted/beamer'
import { Route as UnassistedLightingRouteImport } from './routes/unassisted/lighting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnassistedIndexRoute = UnassistedIndexRouteImport.update({
  id: '/unassisted/',
  path: '/unassisted/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnassistedAudioRoute = UnassistedAudioRouteImport.update({
  id: '/unassisted/audio',
  path: '/unassisted/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const UnassistedBeamerRoute = UnassistedBeamerRouteImport.update({
  id: '/unassisted/beamer',
  path: '/unassisted/beamer',
  getParentRoute: () => rootRouteImport,
} as any)
const UnassistedLightingRoute = UnassistedLightingRouteImport.update({
  id: '/unassisted/lighting',
  path: '/unassisted/lighting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/unassisted/audio': typeof UnassistedAudioRoute
  '/unassisted/beamer': typeof UnassistedBeamerRoute
  '/unassisted/lighting': typeof UnassistedLightingRoute
  '/help/': typeof HelpIndexRoute
  '/unassisted/': typeof UnassistedIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/unassisted/audio': typeof UnassistedAudioRoute
  '/unassisted/beamer': typeof UnassistedBeamerRoute
  '/unassisted/lighting': typeof UnassistedLightingRoute
  '/help': typeof HelpIndexRoute
  '/unassisted': typeof UnassistedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/unassisted/audio': typeof UnassistedAudioRoute
  '/unassisted/beamer': typeof UnassistedBeamerRoute
  '/unassisted/lighting': typeof UnassistedLightingRoute
  '/help/': typeof HelpIndexRoute
  '/unassisted/': typeof UnassistedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/unassisted/audio'
    | '/unassisted/beamer'
    | '/unassisted/lighting'
    | '/help/'
    | '/unassisted/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/unassisted/audio'
    | '/unassisted/beamer'
    | '/unassisted/lighting'
    | '/help'
    | '/unassisted'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/unassisted/audio'
    | '/unassisted/beamer'
    | '/unassisted/lighting'
    | '/help/'
    | '/unassisted/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  UnassistedAudioRoute: typeof UnassistedAudioRoute
  UnassistedBeamerRoute: typeof UnassistedBeamerRoute
  UnassistedLightingRoute: typeof UnassistedLightingRoute
  HelpIndexRoute: typeof HelpIndexRoute
  UnassistedIndexRoute: typeof UnassistedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unassisted/': {
      id: '/unassisted/'
      path: '/unassisted'
      fullPath: '/unassisted/'
      preLoaderRoute: typeof UnassistedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unassisted/audio': {
      id: '/unassisted/audio'
      path: '/unassisted/audio'
      fullPath: '/unassisted/audio'
      preLoaderRoute: typeof UnassistedAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unassisted/beamer': {
      id: '/unassisted/beamer'
      path: '/unassisted/beamer'
      fullPath: '/unassisted/beamer'
      preLoaderRoute: typeof UnassistedBeamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unassisted/lighting': {
      id: '/unassisted/lighting'
      path: '/unassisted/lighting'
      fullPath: '/unassisted/lighting'
      preLoaderRoute: typeof UnassistedLightingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  UnassistedAudioRoute: UnassistedAudioRoute,
  UnassistedBeamerRoute: UnassistedBeamerRoute,
  UnassistedLightingRoute: UnassistedLightingRoute,
  HelpIndexRoute: HelpIndexRoute,
  UnassistedIndexRoute: UnassistedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
