/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AudioRouteImport } from './routes/audio'
import { Route as BeamerRouteImport } from './routes/beamer'
import { Route as LightingRouteImport } from './routes/lighting'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HelpIndexRouteImport } from './routes/help/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioRoute = AudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const BeamerRoute = BeamerRouteImport.update({
  id: '/beamer',
  path: '/beamer',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingRoute = LightingRouteImport.update({
  id: '/lighting',
  path: '/lighting',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/beamer': typeof BeamerRoute
  '/lighting': typeof LightingRoute
  '/settings': typeof SettingsRoute
  '/help/': typeof HelpIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/beamer': typeof BeamerRoute
  '/lighting': typeof LightingRoute
  '/settings': typeof SettingsRoute
  '/help': typeof HelpIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio': typeof AudioRoute
  '/beamer': typeof BeamerRoute
  '/lighting': typeof LightingRoute
  '/settings': typeof SettingsRoute
  '/help/': typeof HelpIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audio' | '/beamer' | '/lighting' | '/settings' | '/help/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio' | '/beamer' | '/lighting' | '/settings' | '/help'
  id:
    | '__root__'
    | '/'
    | '/audio'
    | '/beamer'
    | '/lighting'
    | '/settings'
    | '/help/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioRoute: typeof AudioRoute
  BeamerRoute: typeof BeamerRoute
  LightingRoute: typeof LightingRoute
  SettingsRoute: typeof SettingsRoute
  HelpIndexRoute: typeof HelpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio': {
      id: '/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof AudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beamer': {
      id: '/beamer'
      path: '/beamer'
      fullPath: '/beamer'
      preLoaderRoute: typeof BeamerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting': {
      id: '/lighting'
      path: '/lighting'
      fullPath: '/lighting'
      preLoaderRoute: typeof LightingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioRoute: AudioRoute,
  BeamerRoute: BeamerRoute,
  LightingRoute: LightingRoute,
  SettingsRoute: SettingsRoute,
  HelpIndexRoute: HelpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
