/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAudioRouteImport } from './routes/api/audio'
import { Route as AudioIndexRouteImport } from './routes/audio/index'
import { Route as AudioChannelRouteImport } from './routes/audio/channel'
import { Route as BeamerIndexRouteImport } from './routes/beamer/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as LightingIndexRouteImport } from './routes/lighting/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAudioRoute = ApiAudioRouteImport.update({
  id: '/api/audio',
  path: '/api/audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioIndexRoute = AudioIndexRouteImport.update({
  id: '/audio/',
  path: '/audio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioChannelRoute = AudioChannelRouteImport.update({
  id: '/audio/channel',
  path: '/audio/channel',
  getParentRoute: () => rootRouteImport,
} as any)
const BeamerIndexRoute = BeamerIndexRouteImport.update({
  id: '/beamer/',
  path: '/beamer/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const LightingIndexRoute = LightingIndexRouteImport.update({
  id: '/lighting/',
  path: '/lighting/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/audio/channel': typeof AudioChannelRoute
  '/audio/': typeof AudioIndexRoute
  '/beamer/': typeof BeamerIndexRoute
  '/help/': typeof HelpIndexRoute
  '/lighting/': typeof LightingIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/audio/channel': typeof AudioChannelRoute
  '/audio': typeof AudioIndexRoute
  '/beamer': typeof BeamerIndexRoute
  '/help': typeof HelpIndexRoute
  '/lighting': typeof LightingIndexRoute
  '/settings': typeof SettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/audio': typeof ApiAudioRoute
  '/audio/channel': typeof AudioChannelRoute
  '/audio/': typeof AudioIndexRoute
  '/beamer/': typeof BeamerIndexRoute
  '/help/': typeof HelpIndexRoute
  '/lighting/': typeof LightingIndexRoute
  '/settings/': typeof SettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/audio'
    | '/audio/channel'
    | '/audio/'
    | '/beamer/'
    | '/help/'
    | '/lighting/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/audio'
    | '/audio/channel'
    | '/audio'
    | '/beamer'
    | '/help'
    | '/lighting'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/api/audio'
    | '/audio/channel'
    | '/audio/'
    | '/beamer/'
    | '/help/'
    | '/lighting/'
    | '/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAudioRoute: typeof ApiAudioRoute
  AudioChannelRoute: typeof AudioChannelRoute
  AudioIndexRoute: typeof AudioIndexRoute
  BeamerIndexRoute: typeof BeamerIndexRoute
  HelpIndexRoute: typeof HelpIndexRoute
  LightingIndexRoute: typeof LightingIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audio': {
      id: '/api/audio'
      path: '/api/audio'
      fullPath: '/api/audio'
      preLoaderRoute: typeof ApiAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/': {
      id: '/audio/'
      path: '/audio'
      fullPath: '/audio/'
      preLoaderRoute: typeof AudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio/channel': {
      id: '/audio/channel'
      path: '/audio/channel'
      fullPath: '/audio/channel'
      preLoaderRoute: typeof AudioChannelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beamer/': {
      id: '/beamer/'
      path: '/beamer'
      fullPath: '/beamer/'
      preLoaderRoute: typeof BeamerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lighting/': {
      id: '/lighting/'
      path: '/lighting'
      fullPath: '/lighting/'
      preLoaderRoute: typeof LightingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAudioRoute: ApiAudioRoute,
  AudioChannelRoute: AudioChannelRoute,
  AudioIndexRoute: AudioIndexRoute,
  BeamerIndexRoute: BeamerIndexRoute,
  HelpIndexRoute: HelpIndexRoute,
  LightingIndexRoute: LightingIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
